# -*- coding: utf-8 -*-
"""Step 6: assemble analysis summary markdown from saved outputs."""
import json
from pathlib import Path
import numpy as np
import pandas as pd

OUT = Path(r".\outputs\chol_metab_signature")
w = json.load(open(OUT / "wgcna_summary.json", encoding="utf-8"))
ml = json.load(open(OUT / "ml_summary.json", encoding="utf-8"))
cons = json.load(open(OUT / "consensus_summary.json", encoding="utf-8"))
subs = json.load(open(OUT / "subtype_summary.json", encoding="utf-8"))
prep = json.load(open(OUT / "prep_summary.json", encoding="utf-8"))
sf = pd.read_csv(OUT / "soft_threshold.csv")
mt = pd.read_csv(OUT / "module_trait.csv")
assoc = pd.read_csv(OUT / "cholesterol_gene_assoc.csv")
hub = pd.read_csv(OUT / "hub_genes.csv")
subst = pd.read_csv(OUT / "subtype_stats.csv", index_col=0)
imm = pd.read_csv(OUT / "immune_by_subtype.csv", index_col=0)
pw = pd.read_csv(OUT / "subtype_pairwise_logrank.csv")

chol = pd.read_csv(OUT / "cholesterol_genes.csv")["symbol"].tolist()
shared = set(open(OUT / "shared_genes.txt", encoding="utf-8").read().splitlines())
pool = sorted(set(chol) & shared)
pd.DataFrame({"gene": pool}).to_csv(OUT / "ml_candidate_pool.csv", index=False, encoding="utf-8-sig")

ev_mt = mt[mt.trait == "event"].sort_values("p")
er_mt = mt[mt.trait == "ER"].sort_values("p")
top_assoc = assoc.sort_values("er_t_p").head(8)

lines = []
A = lines.append
A("# 乳腺癌胆固醇代谢基因标签研究 —— 全流程分析汇总（真实数据）")
A("")
A("分析日期：2026-08-07；代码：work/bc_01..bc_06；结果目录：outputs/chol_metab_signature/")
A("")
A("## 0. 流程状态")
A("| 步骤 | 内容 | 状态 |")
A("|---|---|---|")
A("| ① | WGCNA + 胆固醇代谢基因集初筛 | 完成（严格交集为空，见下） |")
A("| ② | LASSO + SVM-RFE 枢纽基因 + ER 判别模型 | 完成（外部验证 AUC 0.922） |")
A("| ③ | 分子分型（一致性聚类 + 预后/免疫/通路） | 完成 |")
A("| ④ | 单细胞定位效应细胞 | 脚本就绪，待数据（GSE176078 / GSE161529） |")
A("| ⑤ | SMR/MR 因果验证 | 脚本就绪，待数据（eQTLGen + BCAC） |")
A("")
A("## 1. 数据与队列")
A("- TCGA-BRCA：952 例（PFI 事件 122，12.8%），59,427 个 STAR 原始计数基因；ER 已知 909 例。")
A("- METABRIC：1,979 例（RFS 事件 803），19,448 个共享基因；ER 已知 1,979 例。")
A("- 全部 TCGA 文件此前已通过 GDC 官方 MD5 校验（4393/4393）。")
A("- 表达量：TCGA log2(CPM+1)；METABRIC 芯片原始强度（z 标准化后比较）。")
A("")
A("## 2. 第①步：WGCNA + 胆固醇基因集")
A("- 网络基因：表达过滤后按 MAD 取前 8,000；软阈值 β=%d（无标度拟合 R²=%.3f，斜率=%.2f）。" % (w["beta"], float(sf.loc[sf.beta == w["beta"], "scale_free_R2"].iloc[0]), float(sf.loc[sf.beta == w["beta"], "slope"].iloc[0])))
A("- 共识别 %d 个模块（≥30 基因）。" % w["n_modules"])
A("- 胆固醇代谢基因集：KEGG hsa00100（类固醇生物合成）+ GO:0008203（胆固醇代谢过程）+ GO:0006695（胆固醇生物合成过程），共 %d 个基因。" % len(chol))
A("- 与 PFI 事件最相关模块：%s（r=%.3f，p=%.4f，BH-FDR=%.2f），%d 个基因。" % (w["event_module"], ev_mt.iloc[0]["cor"], ev_mt.iloc[0]["p"], ev_mt.iloc[0]["padj"], w["event_module_genes"]))
A("- 与 ER 状态最相关模块：%s（r=%.3f，p≈%.0e，BH-FDR≈%.0e）。" % (w["er_module"], er_mt.iloc[0]["cor"], er_mt.iloc[0]["p"], er_mt.iloc[0]["padj"]))
A("- **严格交集（模块 ∩ 胆固醇基因）= 0 个**：事件模块和 ER 模块内均无胆固醇基因；网络内 55 个胆固醇基因中仅 15 个落入正式模块，其余在 <20 基因的小簇中。")
A("- 单基因层面：55 个网络内胆固醇基因无一与 PFI 事件显著相关（最小 Cox p=%.3f，CH25H）；但与 ER 状态强相关的基因包括 %s 等（t 检验 p 最小 %.1e）。" % (assoc.cox_p.min(), "、".join(top_assoc.gene.tolist()[:6]), assoc.er_t_p.min()))
A("- **因严格交集为空，第②步候选池调整为“胆固醇基因 ∩ TCGA/METABRIC 共有可测基因”= %d 个（ml_candidate_pool.csv）；此为本研究有意记录的分析偏差。**" % len(pool))
A("")
A("## 3. 第②步：机器学习 + ER 判别模型")
A("- LASSO（L1 逻辑回归，C=%.3f，5 折 CV 选参）：选中 %d 个基因。" % (ml["C_best"], len(ml["lasso_genes"])))
A("- SVM-RFE（线性 SVM，5 年 landmark 标签）：选中 %d 个基因。" % len(ml["rfe_genes"]))
A("- 两法交集 = **%d 个枢纽基因**：%s" % (len(ml["hub_genes"]), ", ".join(ml["hub_genes"])))
A("- 模型（ER+ vs ER− 判别）：TCGA 内部 5 折 CV AUC = %.3f ± %.3f；全数据 AUC = %.3f。" % (ml["cv_auc_mean"], ml["cv_auc_sd"], ml["full_auc_tcga"]))
A("- **外部验证（METABRIC）：AUC = %.3f（95%% CI %.3f–%.3f）**。" % (ml["external_auc_metabric"], ml["external_auc_ci95"][0], ml["external_auc_ci95"][1]))
A("- 预后（次要、如实报告）：签名每 +1 SD，TCGA PFI HR=%.2f（p=%.3f）；METABRIC RFS HR=%.2f（p=%.1e）。" % (ml["cox"][0]["HR"], ml["cox"][0]["p"], ml["cox"][1]["HR"], ml["cox"][1]["p"]))
A("")
A("## 4. 第③步：分子分型")
A("- 一致性聚类（100 次重采样、80%% 样本）：k=2..6 的 PAC 为 %s；选 k=%d（PAC=%.4f）。" % (", ".join("%d:%.3f" % (int(k), cons["pac"][k]) for k in sorted(cons["pac"], key=int)), cons["k_best"], cons["pac"][str(cons["k_best"])]))
A("- 亚型构成：")
for c in subst.index:
    A("  - C%d：n=%d，ER+ 占比 %.1f%%，PFI 事件 %d，签名均值 %.2f，胆固醇通路评分 %.2f。" % (c, subst.loc[c, "n"], subst.loc[c, "ER_pos_frac"] * 100, subst.loc[c, "events"], subst.loc[c, "signature_mean"], subst.loc[c, "chol_pathway_mean"]))
A("- 生存：4 亚型整体 log-rank p=%.3f；两两比较 p 均 ≥%.3f（122 个事件下无显著差异，如实报告）。" % (subs["multivariate_logrank_p"], pw.padj.min()))
A("- 免疫浸润（代表标志物评分，Kruskal-Wallis）：全部细胞群 p<0.001；C1 在 CD8 T、Treg、NK、B、巨噬细胞评分最高（均值 %.2f–%.2f），C3 普遍最低（%.2f–%.2f），C4 中性粒细胞评分最高（%.2f）。" % (imm["1"].min(), imm["1"].max(), imm["3"].min(), imm["3"].max(), imm["4"].loc["Neutrophil"]))
A("- 亚型间差异表达（每亚型 vs 其余，BH-FDR<0.05）：C1 %d、C2 %d、C3 %d、C4 %d 个基因。" % tuple([int((pd.read_csv(OUT / "subtype_de_genes.csv").padj < 0.05).groupby(pd.read_csv(OUT / "subtype_de_genes.csv").cluster).sum()[c]) for c in range(1, 5)]))
A("- 通路富集（KEGG，FDR 校正）：C2 下调富集氧化磷酸化（hsa00190）、剪接体、细胞周期、DNA 复制等；C3 上调富集氧化磷酸化、核糖体、蛋白加工等；C4 上调富集蛋白加工、细胞周期、蛋白酶体等。GO-BP 与之一致（C2 下调核糖体生物发生、DNA 复制、细胞分裂；C3 上调氧化磷酸化、线粒体组织）。")
A("")
A("## 5. 第④⑤步（待数据，脚本已备好）")
A("- ④ 单细胞：GSE176078（Wu et al., Nat Genet 2021，26 例原发乳腺癌，单细胞+空间）、GSE161529（Pal et al., 2021，约 43 万细胞，覆盖正常/ER+/HER2+/TNBC）。脚本：work/scRNA_breast_template.py")
A("- ⑤ SMR：eQTLGen 全血 cis-eQTL（eqtlgen.org/cis-eqtls.html，含 SMR 格式 BESD）或 GTEx v8 乳腺组织 eQTL；BCAC 乳腺癌 GWAS 汇总统计（Zhang et al. 2020，OncoArray+iCOGS，bcac.ccge.medschl.cam.ac.uk）；SMR 软件（yanglab.westlake.edu.cn/software/smr）。脚本：work/smr_breast_template.sh")
A("")
A("## 6. 主要局限（如实记录）")
A("1. 严格 WGCNA∩胆固醇交集为空，候选池改用“通路基因∩共有可测基因”，属于模板的偏离，已在正文方法中说明。")
A("2. ER 判别模型本质部分反映了 ER 通路生物学（如胆固醇合成基因在 ER+ 高表达），临床新颖性有限，但作为“胆固醇代谢基因标签可区分分子表型”的结论成立。")
A("3. TCGA 事件数少（122），亚型生存差异未达显著；预后结论以 METABRIC（803 事件）为准。")
A("4. 免疫分析为代表性标志物评分（无 MSigDB/CIBERSORT 许可矩阵），发表前建议用 ssGSEA/CIBERSORTx 复核。")
A("5. 通路富集基于 org.Hs.eg.db 本地 KEGG 注释；GO 术语名称需在联网后核对（GO.db 未安装）。")
A("6. 单细胞与 SMR 因网络限制未执行，数据到位后可直接运行已备脚本。")
A("")
A("## 7. 主要产物")
A("- figures/fig1_wgcna.png、fig2_module_trait.png、fig3_signature.png、fig4_roc_er.png、fig5_subtypes.png")
A("- soft_threshold.csv、module_trait.csv、gene_module_map.csv、wgcna_summary.json")
A("- hub_genes.csv、ml_summary.json、signature_tcga.npy、signature_mb.npy、roc_metabric.csv")
A("- tcga_subtypes.csv、immune_scores.csv、immune_by_subtype.csv、subtype_stats.csv、subtype_de_genes.csv、subtype_enrichment.csv、consensus_summary.json")

(OUT / "analysis_summary.md").write_text("\n".join(lines), encoding="utf-8")
print("summary written:", OUT / "analysis_summary.md")